### ISSUE TITLE
Data preprocessing requires a more detailed documentation

### ISSUE THREAD

**Issue by PaolaD** [KlinGenErasmusMC/rnaseq-voila#1]
Hi there! 
I'd like to try your beautiful tool using my data and wanted to follow the pipeline starting from raw data.
However some steps are not really clear to me..
Before using OUTRIDER, I have to normalize the raw counts of all samples using the normalisation_methods.py script? it seems to me like there is a script missing that create the concatenated file with raw counts for all samples and that attach an header to the file

Also, if I understood correctly I can modify the outrider.r script with different paths and filenames? in the script the are several files that I think are not described anywhere (like the metadata.csv file, even if the content is pretty straight-forward)

Could it be possible to have a more detailed documentation on this? 
Best

**Comment by KlinGenErasmusMC** [comment]
Dear Paola,
Sorry for the late reaction. Nice to hear that you want to use this application.
In answer on your questions:

- Before using OUTRIDER you have to make a combined (raw) count file of all samples with the following header: "chr\tstart\tend\tgene\t{BAMTAB}" (in which BAMTAB is a samplename (nr of columns = nr of samples))
 
The script "normalisation_methods.py" is used to create TMM and TPM counts (of the raw counts) and also will be used in OUTRIDER as well as in the application.

OUTRIDER itself uses the raw countfile and the TPM countfile.

-It's true that you need to modify the outrider.R script (and also the  RNAseq filtering app itself) for your own locations.
- an example of the metadata can be found in: [dekker_et_al_rnaseq_metadata.csv](https://github.com/KlinGenErasmusMC/rnaseq-voila/blob/main/metadata/dekker_et_al_rnaseq_metadata.csv)

I hope this will answer your questions,

Best Regards,

Monique

**Comment by PaolaD** [comment]
Dear Monique,
many thanks for you reply. 
I still find the order of commands quite confusing and misleading, that was why I was suggesting to improve the documentation, since this pre-processing step is fundamental to use the notebook.

Please let me know if this is correct:
1. i have to produce individual raw counts - for each sample and genes/introns/transcript file
2. all individual raw counts have to be aggregated - I have to do it myself and add an header
3. use normalisation_methods.py, hoping the user know how to read the argparse in the script, giving as input the aggregated raw count file produced in 2, so that you will obtain the TMM and TPM files
4. here I'm completely lost on what inputs and outputs you should give/obtain... I have to run OUTRIDER on each single sample, but in the same time using the aggregated file obtained in 3? if I obtain several outputs for sample, what should I give to the notebook? should I once again create an aggregated file?

I hope this comment will be accepted positively, not as a critique, but as a way to let you see the difficulties I encountered in understanding this documentation

Best,
Paola

**Comment by KlinGenErasmusMC** [comment]
Dear Paola,

You’re right on step 1-3.
Note step 2: so you create 3 countfiles, one for genes, one for introns and one for exons.
Note for step 3: you probably need a bioinformatician when you want to use this process. The use of TMM and TPM countfiles are optional for the rest of the process.

OUTRIDER is a program (designed by Holger Prokisch; https://bioconductor.org/packages/release/bioc/html/OUTRIDER.html) that compares the counts of a single sample and single fragment to the counts of this fragment of all the other samples.
In one OUTRIDER run this will be performed for all the samples from the countfile (and all the fragments in that countfile) created in step 2. So you don’t have to run OUTRIDER for each sample, just once (per fragment) for all the samples.

OUTRIDER is designed to perform the analysis on gene-level. The created resultfile is used as a inputfile in the voila-application. 
But in our process we also run this program on exon- and intron-countfiles. These are separate OUTRIDER processes and have to be analyzed separately in the voila-application. In the application you chose the sample of interest and look (in this sample) for aberrant fragments.
So you run OUTRIDER 3 times, (genes (on your gene-countfile), introns (on your intron-countfile), exons (on your exon-countfile).

In our process we also used the TPM countfiles to predict which fragments have enough counts to perform the OUTRIDER analysis, and which fragments will not have enough counts, and therefore will be left out. But this is not really necessary.

I hope this make things a little bit more understandable,

Best,
Monique

**Comment by PaolaD** [comment]
Yes, thank you for the prompt reply, now I have a more clear vision on the correct steps order and what to expect
I'll try again!

Best
Paola
