### ISSUE TITLE
outrider.R script: execution halted 

### ISSUE THREAD

**Issue by PaolaD** [KlinGenErasmusMC/rnaseq-voila#3]
Hi!
I'm getting an error while using the outrider.R script. These are the input files I gave to the script:

my metadata file is structured in this way: 
>sample_id;treatment;species;experiment_GS;gender
N001;CHX;fib;provaPipeline;M
N002;untreated;fib;provaPipeline;M
N004;CHX;fib;provaPipeline;M
N007;untreated;fib;provaPipeline;M
N008;CHX;fib;provaPipeline;M
N009;untreated;fib;provaPipeline;M

the gene count:
>chr	start	end	gene	N001	N002	N004	N007	N008	N009
1	11873	14409	DDX11L1	5	2	9	4	30	18
1	14361	29370	WASH7P	9823	2033	3223	9779	8045	2721

and finally the TMP file:
>chr	start	end	gene	N001	N002	N004	N007	N008	N009
1	11873	14409	DDX11L1	0.3596520731757572	0.15518595094829438	0.6780830324747127	0.2935658543281314	2.345174874117139	1.5753367637925393

I then launched the outrider.r script, giving the right paths inside the script:

`Rscript outrider.R 'provaPipeline' 'fib' 'CHX' 'genes'`

However, I got the following error:

>Expected 4 pieces. Missing pieces filled with `NA` in 28526 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
17, 18, 19, 20, ...]. 
Warning message:
Expected 4 pieces. Missing pieces filled with `NA` in 9020 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
17, 18, 19, 20, ...]. 
Error in DESeqDataSet(se, design = design, ignoreRank) : 
  counts matrix should be numeric, currently it has mode: logical
OutriderDataSet -> DESeqDataSetFromMatrix -> DESeqDataSet
Execution halted

the count_subset df have NA in the gene column, and the count_filter dataframe is empty

**Comment by KlinGenErasmusMC** [comment]
Dear Paola,

I think it's the best if you consult a bioinformatician in your direct surroundings to help you futher.

You'll have to make a R countable with chr_start_end_gene in the rowname and only counts in the columns, like:

N001 N002 N004 N007 N008 N009
1_11873_14409_DDX11L1 5 2 9 4 30 18
1_14361_29370_WASH7P 9823 2033 3223 9779 8045 2721

Best regards,

Monique

Van: PaolaD ***@***.***>
Verzonden: donderdag 30 november 2023 16:17
Aan: KlinGenErasmusMC/rnaseq-voila ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [KlinGenErasmusMC/rnaseq-voila] outrider.R script: execution halted (Issue #3)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi!
I'm getting an error while using the outrider.R script. These are the input files I gave to the script:

my metadata file is structured in this way:

sample_id;treatment;species;experiment_GS;gender
N001;CHX;fib;provaPipeline;M
N002;untreated;fib;provaPipeline;M
N004;CHX;fib;provaPipeline;M
N007;untreated;fib;provaPipeline;M
N008;CHX;fib;provaPipeline;M
N009;untreated;fib;provaPipeline;M

the gene count:

chr start end gene N001 N002 N004 N007 N008 N009
1 11873 14409 DDX11L1 5 2 9 4 30 18
1 14361 29370 WASH7P 9823 2033 3223 9779 8045 2721

and finally the TMP file:

chr start end gene N001 N002 N004 N007 N008 N009
1 11873 14409 DDX11L1 0.3596520731757572 0.15518595094829438 0.6780830324747127 0.2935658543281314 2.345174874117139 1.5753367637925393

I then launched the outrider.r script, giving the right paths inside the script:

Rscript outrider.R 'provaPipeline' 'fib' 'CHX' 'genes'

However, I got the following error:

Expected 4 pieces. Missing pieces filled with NA in 28526 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
17, 18, 19, 20, ...].
Warning message:
Expected 4 pieces. Missing pieces filled with NA in 9020 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
17, 18, 19, 20, ...].
Error in DESeqDataSet(se, design = design, ignoreRank) :
counts matrix should be numeric, currently it has mode: logical
OutriderDataSet -> DESeqDataSetFromMatrix -> DESeqDataSet
Execution halted

the count_subset df have NA in the gene column, and the count_filter dataframe is empty

-
