### ISSUE TITLE
Filtering in outrider.R and how to load output to voila

### ISSUE THREAD

**Issue by hermean** [KlinGenErasmusMC/rnaseq-voila#4]
Dear developers,

First thank you for bringing such a beautiful tool!

A few questions I encountered when using this for my own data:
1.	In “outrider.R” script, the filtering step used the following filtering rule:
        "filter counts based on TPM_genes with 95th percentile > 0.1875"
	If I understand correctly, tpm.tsv file would be generated for gene, exon and intron respectively by the normalisation_methods.py. May I know if you used the same filtering criteria for all three?

2.	I obtained the output from outrider.R now, and I was able to set up the server for voila application (I can navigate through your demo data with this server). Could you please give an instruction on how to load my own data to the voila application. The github instructions appear to have a gap between these two steps.

3.	The outrider output for my exon file was listed below. Does the minor difference of missing transcript ID in the last column (as in your demo outrider output) affect voila navigation?

╰─$ head res_outr_expBG01_pax_untreated_exons_counts.csv 
geneID,sampleID,pValue,padjust,zScore,l2fc,rawcounts,normcounts,meanCorrected,theta,aberrant,AberrantBySample,AberrantByGene,padj_rank,FDR_set,treatment,species,experiment_GS,R031,chr,start,end,gene
10_100003847_100003912_R3HCC1L-NM_001256619.2,R001,0.4448672503844058,1,0.73,0.08,395,311.64,295.93,491.56,FALSE,0,0,257173.5,transcriptome-wide,untreated,pax,BG01,299,10,100003847,100003912,R3HCC1L
10_100003847_100003912_R3HCC1L-NM_001256619.2,R002,0.4921346523117049,1,-0.64,-0.06,355,281.37,295.93,491.56,FALSE,0,0,257173.5,transcriptome-wide,untreated,pax,BG01,299,10,100003847,100003912,R3HCC1L
10_100003847_100003912_R3HCC1L-NM_001256619.2,R003,0.9828578923210077,1,-0.03,0,286,294.53,295.93,491.56,FALSE,2,0,257174.5,transcriptome-wide,untreated,pax,BG01,299,10,100003847,100003912,R3HCC1L
10_100003847_100003912_R3HCC1L-NM_001256619.2,R004,0.6324825391935679,1,-0.49,-0.05,280,284.64,295.93,491.56,FALSE,0,0,257173.5,transcriptome-wide,untreated,pax,BG01,299,10,100003847,100003912,R3HCC1L
10_100003847_100003912_R3HCC1L-NM_001256619.2,R005,0.7760281961425951,1,0.31,0.04,351,301.92,295.93,491.56,FALSE,0,0,257173.5,transcriptome-wide,untreated,pax,BG01,299,10,100003847,100003912,R3HCC1L
10_100003847_100003912_R3HCC1L-NM_001256619.2,R006,0.8904038309099112,1,-0.12,-0.01,398,292.47,295.93,491.56,FALSE,0,0,257173.5,transcriptome-wide,untreated,pax,BG01,299,10,100003847,100003912,R3HCC1L

Thanks again, and I really appreciate your kind help.

**Comment by KlinGenErasmusMC** [comment]
1. TPM counts were indeed generated for gene, exon and intron; but in the filtering step (outrider) we only make use of the TPM gene counts. The genes with TPM <0.1875 are filtered out of the resp. gene-, exon- and intron count files.
2.  To load your own data you have to rewrite the voila application for your own locations and your own filenames. For rewriting this script you may need the help of a (bio)informatician.
3. Any difference in the number of columns, or column names effects the working of the voila application. As I mentioned in 2. You might need the help of a (bio)informatician to rewrite the application before running it on your own data.

I hope this helped you out, Good luck!

**Comment by muberracesur** [comment]
Dear Developers, 

I have also a question regarding the filtering process, specifically the selection of the TPM cut-off value of 0.1875. Could you kindly clarify how this threshold was determined? 

Thank you in advance for your response. 
Best regards
